os: osx
osx_image: xcode12.2
language: swift

install:
  - gem install cocoapods
  - pod install --repo-update

script:
  - set -o pipefail && xcodebuild -scheme ParylationDev -workspace Parylation.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.2' build test | xcpretty --color
after_success:
  - bash <(curl -s https://codecov.io/bash)
